name: Event-Driven Tide Automation

on:
  schedule:
    # Automatically scheduled target UTC times for tomorrow:
    - cron: '32 6 * * *'
    - cron: '29 12 * * *'
    - cron: '0 19 * * *'
    - cron: '53 0 * * *'
  workflow_dispatch:

jobs:
  execute_automation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Run Scraping Script
      run: python scrape.py
